### PR TITLE
Run containers without root privileges

### LINKED ISSUE #15: Drop root privileges
Currently the container scripts including libreoffice runs as root. surely it is encapsulated in the container, but as root the attack surface is still much bigger.

Considering the complex nature of parsing office documents leading to security vulnerabilities and that the jodconverter presumably is normally fed with untrusted user data I think this should be changed :)

### PR DESCRIPTION
**Pull request by alangecker**
for increased security :)

closes #15

### CODE REVIEW

**Comment by EugenMayer** [comment]
Thank you for the contribution! Really looking to merge that one

Should we consider using gosu or alikes instead of just USER?

**Comment by EugenMayer** [comment]
To elaborate a little more, i see that:
 - gosu helps us dropping the creds later on when we boot the process, so we can still setup other things with root on entrypoint 
 - we can reload the process with gosu

**Comment by alangecker** [comment]
@EugenMayer 
It works now with gosu and is rebased onto the current master ;)

**Comment by EugenMayer** [comment]
Did you actually test any of the docker images building on this on over at https://github.com/EugenMayer/officeconverter ?

Since they heavily depend on this build, this will be the mandatory test, jodconverter:base is what is used there.

I assume rootless should work, since it just wrapps the java call - the question is if this somehow affects the startup of the headless libreoffice

**Comment by EugenMayer** [comment]
Any new s hew @alangecker ? Thank you for the effort

**Comment by alangecker** [comment]
sorry, didn't manage to find the time to check that :)

I did it now and officeconverter seems to work flawlessly 🎉.  I also ran the tests `make test` without any issues

I only realized that I removed the line `CMD ["--spring.config.additional-location=/etc/app/"]` due to an [error](https://github.com/bigbluebutton/docker/issues/178) and accidentally commited it in this PR which might break it for people using an additional config. I readded the line now, but took the opportunity to add an additional `optional:` prefix as suggested by @lightweight in this issue: https://github.com/bigbluebutton/docker/issues/178

It's definitely not clean to have an unrelated change in the same PR, but hope it's okay^^

**Review by EugenMayer — APPROVED** [review]
LGTM

**Comment by EugenMayer** [comment]
Thank you for your contribution!

**Pull request merged**
